#!/bin/bash

topDir=`pwd -P`

dataDir="data"

resetBuffers="0"

doNothing="0"

#----------------------------------------------------------------------------------------------------

function GetInputFiles()
{
	local dataset="$1"
	local json="$2"
	local output="$3"

	# compile list of runs
	local run_list=""
	for run in `cat "$json" | grep -Po '".*?"' | sed 's/"//g'`
	do
		if [ -n "$run_list" ]
		then
			run_list="$run_list,"
		fi

		run_list="$run_list$run"
	done

	# run search
	echo "* dasgoclient -query \"file dataset=$dataset run in [$run_list]\""

	dasgoclient -query "file dataset=$dataset run in [$run_list]" > "$output"
}

#----------------------------------------------------------------------------------------------------

function ProcessOneDataset()
{
	local dataset="$1"

	local stream="${dataset#*/}"
	stream="${stream%%/*}"

	local era="${dataset#*Run}"
	era="${era%%-*}"

	echo "* $stream, $era"

	if [ "$doNothing" -eq "1" ]
	then
		return 1
	fi

	cd "$topDir"

	# make output directory
	mkdir -p "$dataDir/$era/$stream"
	cd "$dataDir/$era/$stream"

	streamd=`pwd -P`

	# get run numbers
	if [ "$resetBuffers" == "1" ] || [ ! -s "runs" ]
	then
		dasgoclient -query "run dataset=$dataset" > "runs"
	fi

	# make per-fill JSON files
	"$topDir/make_per_fill_json" "runs"

	# make per-fill directory and get list of input files
	for f in fill_*.json
	do
		fill=${f#fill_}
		fill=${fill%.json}

		fd="fill_$fill"

		mkdir -p "$fd"
		mv "$f" "$fd/selection.json"

		if [ "$resetBuffers" == "1" ] || [ ! -s "$fd/files" ]
		then
			GetInputFiles "$dataset" "$fd/selection.json" "$fd/files"
		fi
	done

	# make per-config directories and jobs
	for fd in fill_*
	do
		fill=${fd#fill_}

		# prepare input_commands
		(
		for file in `cat $fd/files`
		do
			echo "process.source.fileNames.append(\"$file\")"
		done
		) > "$fd/input_file_commands"

		# loop over configs
		for cfg in ${configs[*]}
		do
			tag=${cfg%%,*}
			cfg=${cfg#*,}
			xangle_min=${cfg%%,*}
			cfg=${cfg#*,}
			xangle_max=${cfg%%,*}
			cfg=${cfg#*,}
			beta_min=${cfg%%,*}
			cfg=${cfg#*,}
			beta_max=${cfg%%,*}

			cfgd="$fd/$tag"

			mkdir -p "$cfgd"

			cp "$fd/selection.json" "$cfgd/"

			cat "$topDir/template_cfg.py" | sed -e "\
					/\$input_file_commands/ { r $fd/input_file_commands" -e " d };\
					s|\$json_file|$streamd/$cfgd/selection.json|;\
					s|\$xangle_min|$xangle_min|;\
					s|\$xangle_max|$xangle_max|;\
					s|\$beta_min|$beta_min|;\
					s|\$beta_max|$beta_max|;\
					s|\$output_file|output.root|;\
				" > "$cfgd/cfg.py"

			cat "$topDir/template_job" | sed "\
					s|\$WORK_DIR|$streamd/$cfgd|;\
					s|\$CMSSW_DIR|$CMSSW_BASE|;\
					s|\$EXEC_SUB_DIR|fill_$fill/$stream/$tag|;\
					s|\$OUTPUT_DIR|$output_dir|;\
					s|\$OUTPUT_TAG|fill${fill}_${tag}_${stream}|;\
				" > "$cfgd/job"

			chmod u+x "$cfgd/job"

			cat "$topDir/template_CheckRootFile.cc" | sed "\
					s|\$file|output.root|;\
				" > "$cfgd/CheckRootFile.cc"
		done
	done
}

#----------------------------------------------------------------------------------------------------

function RunOneDataset
{
	ProcessOneDataset "$1" #&
}

#----------------------------------------------------------------------------------------------------

make || exit 1



# ----- 2016 settings -----

output_dir="/eos/cms/store/group/phys_pps/reconstruction/2016/physics_runs/version-UL-2"

configs=(
	"xangle185_beta0.40,184,186,0.39,0.41"
)

##RunOneDataset "/DoubleEG/Run2016B-21Feb2020_UL2016_HIPM_rsb-v1/AOD"
##RunOneDataset "/DoubleEG/Run2016C-21Feb2020_UL2016_HIPM-v1/AOD" # very low block presence
##RunOneDataset "/DoubleEG/Run2016G-21Feb2020_UL2016-v1/AOD"
#
#RunOneDataset "/JetHT/Run2016B-21Feb2020_ver2_UL2016_HIPM-v1/AOD"
#RunOneDataset "/JetHT/Run2016C-21Feb2020_UL2016_HIPM-v1/AOD"
##RunOneDataset "/JetHT/Run2016G-21Feb2020_UL2016-v1/AOD" # on tape only
#
#RunOneDataset "/SingleElectron/Run2016B-21Feb2020_ver2_UL2016_HIPM-v1/AOD"
#RunOneDataset "/SingleElectron/Run2016C-21Feb2020_UL2016_HIPM-v1/AOD"
#RunOneDataset "/SingleElectron/Run2016G-21Feb2020_UL2016-v1/AOD"
#
#RunOneDataset "/SingleMuon/Run2016B-21Feb2020_ver2_UL2016_HIPM-v1/AOD"
#RunOneDataset "/SingleMuon/Run2016C-21Feb2020_UL2016_HIPM-v1/AOD"
##RunOneDataset "/SingleMuon/Run2016G-21Feb2020_UL2016-v1/AOD"
#
#RunOneDataset "/ZeroBias/Run2016B-21Feb2020_ver1_UL2016_HIPM-v1/AOD"
#RunOneDataset "/ZeroBias/Run2016C-21Feb2020_UL2016_HIPM-v1/AOD"
##RunOneDataset "/ZeroBias/Run2016G-21Feb2020_UL2016-v1/AOD" # on tape only

configs=(
	"xangle140_beta0.40,139,141,0.39,0.41"
)

##RunOneDataset "/DoubleEG/Run2016H-21Feb2020_UL2016-v1/AOD"
#
#RunOneDataset "/JetHT/Run2016H-21Feb2020_UL2016-v1/AOD"
#
#RunOneDataset "/SingleElectron/Run2016H-21Feb2020_UL2016-v2/AOD"
#
##RunOneDataset "/SingleMuon/Run2016H-21Feb2020_UL2016-v1/AOD"
#
#RunOneDataset "/ZeroBias/Run2016H-21Feb2020_UL2016-v1/AOD"



# ----- 2017 settings -----

output_dir="/eos/cms/store/group/phys_pps/reconstruction/2017/physics_runs/version-UL-2"

configs=(
	"xangle120_beta0.40,119,121,0.39,0.41"
	"xangle130_beta0.40,129,131,0.39,0.41"
	"xangle140_beta0.40,139,141,0.39,0.41"
	"xangle150_beta0.40,149,151,0.39,0.41"
)

#RunOneDataset "/DoubleEG/Run2017B-09Aug2019_UL2017-v1/AOD" # very low block presence
#RunOneDataset "/DoubleEG/Run2017C-09Aug2019_UL2017-v1/AOD"
#RunOneDataset "/DoubleEG/Run2017D-09Aug2019_UL2017-v1/AOD"

RunOneDataset "/MET/Run2017B-09Aug2019_UL2017_rsb-v1/AOD" # very low block presence
RunOneDataset "/MET/Run2017C-09Aug2019_UL2017_rsb-v1/AOD"
RunOneDataset "/MET/Run2017D-09Aug2019_UL2017_rsb-v1/AOD"

RunOneDataset "/SingleElectron/Run2017B-09Aug2019_UL2017-v1/AOD"
RunOneDataset "/SingleElectron/Run2017C-09Aug2019_UL2017-v1/AOD"
#RunOneDataset "/SingleElectron/Run2017D-09Aug2019_UL2017-v1/AOD" # very low block presence

RunOneDataset "/SingleMuon/Run2017B-09Aug2019_UL2017-v1/AOD"
#RunOneDataset "/SingleMuon/Run2017C-09Aug2019_UL2017-v1/AOD"
RunOneDataset "/SingleMuon/Run2017D-09Aug2019_UL2017-v1/AOD"

RunOneDataset "/ZeroBias/Run2017B-09Aug2019_UL2017-v1/AOD"
RunOneDataset "/ZeroBias/Run2017C-09Aug2019_UL2017-v1/AOD"
#RunOneDataset "/ZeroBias/Run2017D-09Aug2019_UL2017-v1/AOD" # low block presence


configs=(
	"xangle120_beta0.30,119,121,0.29,0.31"
	"xangle130_beta0.30,129,131,0.29,0.31"
	"xangle140_beta0.30,139,141,0.29,0.31"
	"xangle150_beta0.30,149,151,0.29,0.31"
)

#RunOneDataset "/DoubleEG/Run2017E-09Aug2019_UL2017-v1/AOD"
#RunOneDataset "/DoubleEG/Run2017F-09Aug2019_UL2017-v1/AOD" # very low block presence

RunOneDataset "/MET/Run2017E-09Aug2019_UL2017-v1/AOD"
#RunOneDataset "/MET/Run2017F-09Aug2019_UL2017_rsb-v1/AOD" # very low block presence

RunOneDataset "/SingleElectron/Run2017E-09Aug2019_UL2017-v1/AOD"
RunOneDataset "/SingleElectron/Run2017F-09Aug2019_UL2017_rsb-v2/AOD"

RunOneDataset "/SingleMuon/Run2017E-09Aug2019_UL2017-v1/AOD"
RunOneDataset "/SingleMuon/Run2017F-09Aug2019_UL2017-v1/AOD"

RunOneDataset "/ZeroBias/Run2017E-09Aug2019_UL2017-v1/AOD"
RunOneDataset "/ZeroBias/Run2017F-09Aug2019_UL2017-v1/AOD"



# ----- 2018 settings -----

output_dir="/eos/cms/store/group/phys_pps/reconstruction/2018/physics_runs/version-UL-2"

configs=(
	"xangle130_beta0.25,129.9,130.1,0.24,0.26"

	"xangle130_beta0.30,129.9,130.1,0.29,0.31"
	#"xangle138_beta0.30,130.1,145.0,0.29,0.31"
	"xangle140_beta0.30,139.9,140.1,0.29,0.31"
	"xangle150_beta0.30,149.9,150.1,0.29,0.31"
	#"xangle152_beta0.30,145.0,159.9,0.29,0.31"
	"xangle160_beta0.30,159.9,160.1,0.29,0.31"
)

## RunOneDataset "/BTagMu/Run2018A-12Nov2019_UL2018-v1/AOD"
## RunOneDataset "/BTagMu/Run2018B-12Nov2019_UL2018-v1/AOD"
## #RunOneDataset "/BTagMu/Run2018C-12Nov2019_UL2018-v1/AOD" --> tape only
## RunOneDataset "/BTagMu/Run2018D-12Nov2019_UL2018-v1/AOD"

## RunOneDataset "/Charmonium/Run2018A-12Nov2019_UL2018_rsb-v1/AOD"
## RunOneDataset "/Charmonium/Run2018B-12Nov2019_UL2018-v1/AOD"
## RunOneDataset "/Charmonium/Run2018C-12Nov2019_UL2018_rsb_v2-v2/AOD"
## #RunOneDataset "/Charmonium/Run2018D-12Nov2019_UL2018-v1/AOD" --> blocks incomplete?

##RunOneDataset "/DoubleMuon/Run2018A-12Nov2019_UL2018-v2/AOD"
#RunOneDataset "/DoubleMuon/Run2018B-12Nov2019_UL2018-v2/AOD"
#RunOneDataset "/DoubleMuon/Run2018C-12Nov2019_UL2018-v2/AOD"
#RunOneDataset "/DoubleMuon/Run2018D-12Nov2019_UL2018-v3/AOD"

#	RunOneDataset "/EGamma/Run2018A-12Nov2019_UL2018-v2/AOD"
#	RunOneDataset "/EGamma/Run2018B-12Nov2019_UL2018-v2/AOD"
#	RunOneDataset "/EGamma/Run2018C-12Nov2019_UL2018-v2/AOD"
#	RunOneDataset "/EGamma/Run2018D-12Nov2019_UL2018-v4/AOD"

#RunOneDataset "/JetHT/Run2018A-12Nov2019_UL2018-v2/AOD"
#RunOneDataset "/JetHT/Run2018B-12Nov2019_UL2018-v2/AOD"
#RunOneDataset "/JetHT/Run2018C-12Nov2019_UL2018_rsb-v1/AOD" # on tape only
#RunOneDataset "/JetHT/Run2018D-12Nov2019_UL2018_rsb-v1/AOD"

#RunOneDataset "/MET/Run2018A-12Nov2019_UL2018_rsb-v1/AOD"
##RunOneDataset "/MET/Run2018B-12Nov2019_UL2018_rsb-v1/AOD" # on tape only
#RunOneDataset "/MET/Run2018C-12Nov2019_UL2018_rsb-v1/AOD"
##RunOneDataset "/MET/Run2018D-12Nov2019_UL2018_rsb-v2/AOD" # on tape only

##RunOneDataset "/MuOnia/Run2018A-12Nov2019_UL2018-v1/AOD" # on tape only
#RunOneDataset "/MuOnia/Run2018B-12Nov2019_UL2018-v1/AOD"
##RunOneDataset "/MuOnia/Run2018C-12Nov2019_UL2018-v1/AOD" # on tape only
#RunOneDataset "/MuOnia/Run2018D-12Nov2019_UL2018-v1/AOD" 

#RunOneDataset "/MuonEG/Run2018A-12Nov2019_UL2018_rsb-v1/AOD"
##RunOneDataset "/MuonEG/Run2018B-12Nov2019_UL2018-v1/AOD" # on tape only
##RunOneDataset "/MuonEG/Run2018C-12Nov2019_UL2018-v1/AOD" # on tape only
##RunOneDataset "/MuonEG/Run2018D-12Nov2019_UL2018_rsb-v1/AOD" # on tape only

##RunOneDataset "/SingleMuon/Run2018A-12Nov2019_UL2018_rsb-v1/AOD" # some blocks possibly missing
#RunOneDataset "/SingleMuon/Run2018B-12Nov2019_UL2018-v2/AOD" # low file percentage
#RunOneDataset "/SingleMuon/Run2018C-12Nov2019_UL2018-v2/AOD" # essentially no files available
#RunOneDataset "/SingleMuon/Run2018D-12Nov2019_UL2018-v4/AOD"

#RunOneDataset "/Tau/Run2018A-12Nov2019_UL2018_rsb-v1/AOD"
#RunOneDataset "/Tau/Run2018B-12Nov2019_UL2018-v1/AOD" # on tape only
#RunOneDataset "/Tau/Run2018C-12Nov2019_UL2018-v1/AOD"
#RunOneDataset "/Tau/Run2018D-12Nov2019_UL2018-v1/AOD" # on tape only

##RunOneDataset "/ZeroBias/Run2018A-12Nov2019_UL2018-v2/AOD"
#RunOneDataset "/ZeroBias/Run2018B-12Nov2019_UL2018-v2/AOD"
#RunOneDataset "/ZeroBias/Run2018C-12Nov2019_UL2018_rsb-v1/AOD"
#RunOneDataset "/ZeroBias/Run2018D-12Nov2019_UL2018_rsb-v1/AOD"
